spring:
  webflux:
    base-path: /api/${API_VERSION}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://${DATABASE_HOSTNAME}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${secrets.DATABASE_USERNAME_FILE}
    password: ${secrets.DATABASE_PASSWORD_FILE}

server:
  port: ${API_PORT}

api:
  version: ${API_VERSION}

springdoc:
  api-docs:
    path: /openapi
  swagger-ui:
    path: /docs
